### ISSUE TITLE
Document known issues, common RC2 errors, and workarounds

### ISSUE THREAD

**Issue by natemcmaster** [aspnet/EntityFramework.Docs#157]
## Common errors

- [x] Restore with out imports cref https://github.com/NuGet/Home/issues/2644 https://github.com/aspnet/EntityFramework/issues/5176
```
Package Ix-Async 1.2.5 is not compatible with netcoreapp1.0 (.NETCoreApp,Version=v1.0). Package Ix-Async 1.2.5 supports:
      - net40 (.NETFramework,Version=v4.0)
      - net45 (.NETFramework,Version=v4.5)
      - portable-net45+win8+wp8 (.NETPortable,Version=v0.0,Profile=Profile78)
    Package Remotion.Linq 2.0.2 is not compatible with netcoreapp1.0 (.NETCoreApp,Version=v1.0). Package Remotion.Linq 2.0.2 supports:
      - net35 (.NETFramework,Version=v3.5)
      - net40 (.NETFramework,Version=v4.0)
      - net45 (.NETFramework,Version=v4.5)
      - portable-net45+win8+wp8+wpa81 (.NETPortable,Version=v0.0,Profile=Profile259)
```
- [x] How to install tools cref https://github.com/aspnet/EntityFramework/issues/5272

- [x] dotnet-ef in powershell executes successfully but shows "Native command error" because of output to stderr https://github.com/aspnet/EntityFramework/issues/5012

- [x] This error
```
Cannot execute this command because 'Microsoft.EntityFrameworkCore.Tools' is not installed in project 'src\ConsoleApp1'. Add 'Microsoft.EntityFrameworkCore.Tools' to the 'tools' section in project.json.
```

## Issues with a workaround

 - [x] Can't use CLI commands on a `netstandard` library. cref https://github.com/dotnet/cli/issues/2645
 - [x] Powershell 3 error
```
The expression after '&' in a pipeline element produced an object that was not valid. It must result in a command name, a script block, or a CommandInfo object.
```
