### ISSUE TITLE
Overall plan for 3.x docs

### ISSUE THREAD

**Issue by ajcvickers** [aspnet/EntityFramework.Docs#1675]
- [x] Update banner/readme to reflect the present
  - [x] EF Core
  - [x] EF6
- [x] Ensure dependencies are correct and consistent
   - [x] .NET versions supported - consider consolidating into a single page #1635
- [x] Move wiki information into repo markdown files
- [x] Update issue templates
- [x] Cleanup table of contents #1517
- [x] Initial issue scrub (@ajcvickers)
- [x] Samples:
  - [x] Move all samples to docs repo #487
  - [x] Update for 3.0 #1074
- [x] Create a first-class story for Microsoft.Data.Sqlite docs (@bricelam)
- [x] Update "data access technology for Visual Studio" docs - moved to #2053

**Comment by bricelam** [comment]
I think the Microsoft.Data.Sqlite docs would be most discoverable if they went next to the ADO.NET and SqlClient docs: https://docs.microsoft.com/dotnet/framework/data/adonet/

**Comment by roji** [comment]
@bricelam agree, and on a totally unrelated note the ADO.NET and SqlClient docs should also move out of .NET Framework (or be duplicated into .NET Core or something...). I'll try to see with @mairaw what the plans are after we stop doing bug fixes on 3.1.

**Comment by bricelam** [comment]
Here is a list of topics for Microsoft.Data.Sqlite:
* Overview
* Connection strings
  * (Link to https://docs.microsoft.com/dotnet/framework/data/adonet/connection-strings)
* Data type mappings
  * (Like https://docs.microsoft.com/dotnet/framework/data/adonet/sql-server-data-type-mappings)
  * (Update https://github.com/aspnet/Microsoft.Data.Sqlite/wiki/Data-Type-Mappings)
  * (Adapt DateAndTimeSample)
* Command timeouts/Busy retries
* Transactions
  * (Adapt DirtyReadSample)
* Batching
  * (Adapt BatchingSample)
  * (Mention DbDataReader.NextResult())
* Result metadata
  * (Adapt ResultMetadataSample)
* SQlite features
  * In-memory databases
    * (Adapt InMemorySample)
    * (Port https://www.bricelam.net/2015/12/10/shareable-in-memory-databases.html)
  * User-defined functions
    * (Adapt AggregateFunctionSample)
    * (Adapt RegularExpressionSample)
    * (Adapt ScalarFunctionSample)
  * Collation
    * (Adapt CollationSample)
  * Encryption
    * (Adapt EncryptionSample)
    * (Port https://www.bricelam.net/2016/06/13/sqlite-encryption.html)
  * BLOB I/O streams
    * (Adapt StreamingSample)
  * Using a custom version of SQLite
  * Interop/SQLitePCL.raw/handles
    * (Adapt InteropSample)
* Limitations
  * Async
    * (Adapt AsyncSample)
  * Bulk insert
    * (Adapt BulkInsertSample)
    * (Port https://www.bricelam.net/2017/07/20/sqlite-bulk-insert.html)
  * DbConnection.GetSchema()
  * System.Transactions aspnet/EntityFrameworkCore#13823
  * DataAdapter aspnet/EntityFrameworkCore#13838
  * Xamarin.iOS #597
    * (Mention SQLitePCL.Batteries_V2.Init())
* Comparison to System.Data.SQLite
  * (Adapt https://www.bricelam.net/2018/05/24/microsoft-data-sqlite-2-1.html#comment-3980643870)
  * (Mention less connection string keywords and no connection flags)
  * (No authorization) aspnet/EntityFrameworkCore#13835
  * (No data change notifications) aspnet/EntityFrameworkCore#13827    
  * (No virtual table modules) aspnet/EntityFrameworkCore#13823
