### ISSUE TITLE
Migrations

### ISSUE THREAD

**Issue by natemcmaster** [aspnet/EntityFramework.Docs#204]
Our getting started guides mentions migrations and shows how to add one, but we have a dedicated section to document the rest of what is possible with migrations.

Some specific things to cover in addition to a general overview
 - [x] Overview of how migrations works, something like the content at the start of [EF6.x Migrations in Team Environments](https://msdn.microsoft.com/en-us/library/dn481501(v=vs.113).aspx)
 - [x] how to use --startup-project (#294)
 - [x] Multiple projects and migrations (#43)
 - [x] Custom Migrations history table (#371)
 - [x] IDbContextFactory
 - [x] [Custom Migrations Operations](https://romiller.com/2013/02/27/ef6-writing-your-own-code-first-migration-operations/)
 - [x] Using IMigrator (#518)

**Comment by rowanmiller** [comment]
Agreed, this is on my list under a "Database Schema Management" section I'm going to write 😄

**Comment by bricelam** [comment]
Note to documenter, we also wanted to reference this from the `Enable-Migrations` command.

**Comment by bricelam** [comment]
Turns out there's already some pretty good docs at https://docs.microsoft.com/aspnet/core/data/ef-mvc/migrations

**Comment by rosieks** [comment]
Could you write tutorial how to use migrations together with VSTS Build & Release.
